"""update database with the timezone

Revision ID: 1efb5238039f
Revises: ae810e5ab525
Create Date: 2026-08-16 15:18:16.869586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1efb5238039f'
down_revision: Union[str, Sequence[str], None] = 'ae810e5ab525'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userrefreshtoken', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('userrefreshtoken', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('userrefreshtoken', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('userrefreshtoken', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_column('userrefreshtoken', 'revovked_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userrefreshtoken', sa.Column('revovked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('userrefreshtoken', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('userrefreshtoken', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('userrefreshtoken', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('userrefreshtoken', 'revoked_at')
    # ### end Alembic commands ###
