"""added phone verification column

Revision ID: 31f1f1b3727f
Revises: e41d822d478f
Create Date: 2026-08-31 23:27:30.924761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f1f1b3727f'
down_revision: Union[str, Sequence[str], None] = 'e41d822d478f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('phone_verified', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'phone_verified')
    # ### end Alembic commands ###
