"""initial migration

Revision ID: a8fe1b47fb7b
Revises: 
Create Date: 2026-07-27 00:54:40.743631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8fe1b47fb7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver', 'vehicle_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('vehicle_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
