"""Added phone_verified column

Revision ID: e41d822d478f
Revises: fdfe3925f1e2
Create Date: 2026-08-26 10:38:15.956750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41d822d478f'
down_revision: Union[str, Sequence[str], None] = 'fdfe3925f1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_verified', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_verified')
    # ### end Alembic commands ###
